# Generated by Django 4.2.2 on 2023-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nDevis', models.IntegerField()),
                ('nFr', models.IntegerField()),
                ('nCom', models.IntegerField()),
                ('dateCom', models.DateField()),
                ('montantCde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refProd', models.IntegerField()),
                ('nCom', models.IntegerField()),
                ('prixProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qteCmd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refProd', models.IntegerField()),
                ('nDevis', models.IntegerField()),
                ('prixProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qteProd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nFr', models.IntegerField()),
                ('nDevis', models.IntegerField()),
                ('dateDevis', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nFact', models.IntegerField()),
                ('nCom', models.IntegerField()),
                ('montantFact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateFacr', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nFr', models.IntegerField()),
                ('societe', models.CharField(max_length=150)),
                ('tele', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nFact', models.IntegerField()),
                ('refProd', models.IntegerField()),
                ('nBon', models.IntegerField()),
                ('prixLiv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qteLiv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refProd', models.IntegerField()),
                ('description', models.TextField()),
                ('marque', models.CharField(max_length=500)),
            ],
        ),
    ]
